### ISSUE TITLE
感谢大佬的分享

### ISSUE THREAD

**Issue by xiyuvi** [GentleCP/corpwechat-bot#1]
请问可以出一个和腾讯云开发的定时器联动的教程吗？  萌新想搞一个定时回复，不会配置0.0

**Comment by GentleCP** [comment]
我没有用过腾讯云的定时器（看了下文档好像和linux自带的crontab差不多），不过看你的需求应该是在特定时间段发送消息是吧？ 这个功能的实现应该有很多选项，例如`crontab` （定时执行脚本），python的`apscheduler` (定时任务库) ，这些都可以达到你需要的定时回复任务。这些内容网上有很多教程可以参考。

我个人推荐使用`crontab` ，你可以先利用`corpwechatbot`编写好一个`python` 脚本，例如`hello.py` (功能是发送你好到企业微信) ，然后我希望每天9: 00 都能定时收到该信息，在linux终端输入`crontab -e` ，填入如下信息：
```shell
0 9 * * * python3 hello.py
```

**Comment by xiyuvi** [comment]
谢谢您的指点，请问下个版本可以设置成可以同时配置好几个发送信息，然后随机挑一条发送过去吗

**Comment by GentleCP** [comment]
同时配置好几个消息随机发送，不知道为什么会有这个需求？（想不到使用场景）像接口一次性传入多个消息（例如消息队列），然后逐条发送，这种是会考虑的，但是不知道随机是有什么作用，不过这个问题现在也很好解决，只要你自己设置一个消息列表，例如:
```python
msgs = [
    'hello',
    'world',
    'nice to meet u',
]
```
然后在发送前你用random函数初始化一个种子，从消息列表中随机取出一条消息（可以通过索引下标也可以直接通过列表随机取元素），用`send_xxx()`方法发送即可，并不需要专门为这个做开发，希望能解答你的疑惑。

**Comment by xiyuvi** [comment]
我想搞一个以我家猫的角度定时提醒摸他的提示，所以可能换几个内容比较好一些。我不懂py，谢谢你的思路，我去查文档研究一下
