### ISSUE TITLE
可以实现消息自动回复吗？

### ISSUE THREAD

**Issue by liuing-org** [GentleCP/corpwechat-bot#11]
类似状态消息，当我不能及时回复内部联系人或外部联系人的消息时，能代替我回复一条状态消息吗

**Comment by GentleCP** [comment]
你说的场景应该是别人直接私聊你的企业微信号，然后自动回复是吧，腾讯貌似没有提供账号本身的消息推送接口，所有接口都是针对应用和机器人的，类似的如群内@机器人 回复消息这种是可以的。 参考：https://work.weixin.qq.com/nl/act/p/bfbc0708645f4551
