### ISSUE TITLE
企业微信接收信息功能

### ISSUE THREAD

**Issue by xiaoqiangclub** [GentleCP/corpwechat-bot#13]
建议可以建企业微信接收信息的接口一并给写了

**Comment by GentleCP** [comment]
参考：https://gist.github.com/GentleCP/5d02f4e84b8c8905bcf67643223cd499 ， 这是一个接收消息的例子

**Comment by yuanjie-ai** [comment]
回调接口 怎么弄

**Comment by yuanjie-ai** [comment]
> 参考：[https://gist.github.com/GentleCP/5d02f4e84b8c8905bcf67643223cd499，](https://gist.github.com/GentleCP/5d02f4e84b8c8905bcf67643223cd499%EF%BC%8C) 这是一个接收消息的例子

打不开

**Comment by GentleCP** [comment]
> > 参考：[https://gist.github.com/GentleCP/5d02f4e84b8c8905bcf67643223cd499，](https://gist.github.com/GentleCP/5d02f4e84b8c8905bcf67643223cd499%EF%BC%8C) 这是一个接收消息的例子
> 
> 打不开

把逗号移开打开

**Comment by GentleCP** [comment]
> 回调接口 怎么弄

好好看文档：https://corpwechatbot.gentlecp.com/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/callback_configuration/
