### ISSUE TITLE
util.py可能存在python3兼容问题

### ISSUE THREAD

**Issue by dalao-B** [GentleCP/corpwechat-bot#2]
python3不支持这个语法吧
![image](https://user-images.githubusercontent.com/48510418/117749080-bbe78f80-b243-11eb-86cf-2939dc10a3dd.png)
![image](https://user-images.githubusercontent.com/48510418/117749103-c570f780-b243-11eb-8acf-7d188545cfa3.png)

**Comment by GentleCP** [comment]
确实不该传入这两个参数，请问你是在实例化对象的时候报出这个异常的吗? 但这个貌似不影响正常使用，可否提供你报异常的代码，如果影响不大，就在下个版本再进行修复。
![image](https://user-images.githubusercontent.com/38175267/117750485-108c0a00-b246-11eb-8bdb-c8355e3bcdc8.png)

**Comment by dalao-B** [comment]
对，就是在实例化的时候报的
![image](https://user-images.githubusercontent.com/48510418/117751243-55fd0700-b247-11eb-9f58-08e6a5ff9ab4.png)

**Comment by GentleCP** [comment]
验证确实如此，该问题主要是单例模式设置不当引起的，我会尽快修复并发布到下一个版本，如果着急的话，你可以先使用`0.2.0`及以前的版本，不会出现这个问题：
```shell
pip install corpwechatbot==0.2.0
```

**Comment by GentleCP** [comment]
你好，该问题已在新版本`v0.2.4`中得到解决，你可以使用最新版本或者继续采用`v0.2.0`及之前的版本，具体可查看[changelog](https://github.com/GentleCP/corpwechat-bot/blob/master/docs/changelog.md)

另外，感谢你提出的问题，希望以后也能多多提供意见，💖

**Comment by dalao-B** [comment]
好的 多谢
