### ISSUE TITLE
因为是局域网，想用bot发送消息，但是只能是默认的群，不能指定其他群机器人

### ISSUE THREAD

**Issue by worldyouwyl** [GentleCP/corpwechat-bot#24]
局域网，想要各自的群机器人，分别发送消息

**Comment by GentleCP** [comment]
指定机器人的key即可，通过创建不同的key的对象

**Comment by worldyouwyl** [comment]
bot = CorpWechatBot()
bot.send_text(content='Hello World!')
根目录的已经在用了，这个bot不能传参，只能发送到根目录的key
可以传参的话，一台机器，就能控制好几个机器人群了

内网IP不好加入白名单，下面的用不了
app.send_text(content="如果我是DJ，你会爱我吗？")

**Comment by GentleCP** [comment]
每个 CorpWechatBot() 都是一个独立的对象，你只需要在创建的时候给他传入key 参数，就可以利用多个不同的机器人发送
