### ISSUE TITLE
【ERROR】 发送失败!，原因：not allow operate another agent with this accesstoken.

### ISSUE THREAD

**Issue by Sloaix** [GentleCP/corpwechat-bot#3]
位于

```https://github.com/GentleCP/corpwechat-bot/blob/29d396dc13b82243a3960b33a83ba4c4aea87d23/corpwechatbot/app.py```

的源码
```python
CUR_PATH = Path(__file__)
TOKEN_PATH = CUR_PATH.parent.joinpath('token.txt')  # 存储在本项目根目录下
```
缓存了token，但是根据企业微信的api的报错来看，not allow operate another agent with this accesstoken，针对不同的自建第三方应用，需要不同的token，这里缓存的token应该对此作出调整。

复现步骤，创建两个不同的自建应用。

分别使用不同的应用的corpsecret和agentid创建AppMsgSender实例，用不同的AppMsgSender推送消息到客户端。

**Comment by GentleCP** [comment]
你好，新版本[v0.3.0](https://pypi.org/project/corpwechatbot/0.3.0/)已支持多应用的创建，每个应用的token各自存储

**Comment by Sloaix** [comment]
这修复好神速，good job。😂

**Comment by GentleCP** [comment]
> 这修复好神速，good job。😂

^_^，另外，v0.3.0版本中我忘记考虑了不同企业同样id的应用产生的token冲突问题，已经在v0.3.1中解决，具体查看[changelog](https://github.com/GentleCP/corpwechat-bot/blob/master/docs/changelog.md)
