### ISSUE TITLE
有没有办法推送到个人微信呢

### ISSUE THREAD

**Issue by baifengbai** [GentleCP/corpwechat-bot#4]

**Comment by GentleCP** [comment]
企业微信是支持个人微信接收消息的，当你加入企业微信后，可以在通讯录中找到你的企业微信，通过自定义应用发送的消息会被显示

**Comment by KongNan** [comment]
开始我也卡在这儿了。经查，支持发送到扫描微信插件二维码后通过身份验证的企业员工对应的个人微信。

**Comment by GentleCP** [comment]
👍感谢指出，另外企业微信app新消息通知中可以设置 **仅在企业微信中接收消息** ，如果开启了，就不会发送到个人微信上。
另外，感谢第一笔赞助，OVO

**Comment by KongNan** [comment]
> 👍感谢指出，另外企业微信app新消息通知中可以设置 **仅在企业微信中接收消息** ，如果开启了，就不会发送到个人微信上。
> 另外，感谢第一笔赞助，OVO

嗯，我说在企业微信后台找不到这个设置了呢，原来在客户端。（我先前操作取消过，所以并未影响使用，并且还好纯微信用户不存在这一问题）
