### ISSUE TITLE
大佬能支持下mpnews这种类型的图文发送吗 拜托感谢

### ISSUE THREAD

**Issue by dalao-B** [GentleCP/corpwechat-bot#5]
大佬能支持下mpnews这种类型的图文发送吗 拜托感谢

**Comment by GentleCP** [comment]
该类型消息和普通消息一致，只是图文内容会存储在企业微信，因此我在一开始的时候没考虑，目前想不到什么必须要用这种消息的场景（可以用普通的图文消息替代），可否提供你需要支持这种消息的详细理由，如果合适我会尽快添加支持该系列的消息，如果需求不大，可能会延后一段时间和其他的内容一起发布在下个版本中。
![image](https://user-images.githubusercontent.com/38175267/118746991-c4ffde80-b88b-11eb-97b3-062cf20dbd16.png)

**Comment by dalao-B** [comment]
普通图文无法添加内容，mpnews图文可以实现图文消息的内容，支持html标签，不超过666 K个字节（支持id转译），这个现在看来是很有必要的，拜托大佬抽空更一下，感谢

**Comment by dalao-B** [comment]
mpnews content内容中支持html标签，可添加img等标签，能够实现多图片显示等

**Comment by GentleCP** [comment]
好的，我会加到下个版本的更新计划中

**Comment by dalao-B** [comment]
那请问大佬下个版本预计什么时候会发呢，我评估一下是否能赶得上更新

**Comment by GentleCP** [comment]
最快本周末吧，因为工作日我没有时间

**Comment by dalao-B** [comment]
好的 多谢，期待下次更新

**Comment by GentleCP** [comment]
你好，新版本已更新，添加了对mpnews消息的支持，还有一些小改动，具体请参考[changelog](https://github.com/GentleCP/corpwechat-bot/blob/master/docs/changelog.md)
