### ISSUE TITLE
有没有计划出搭建服务端的功能？

### ISSUE THREAD

**Issue by photkey** [GentleCP/corpwechat-bot#6]
首先非常感谢您分享这么好用的项目！以前用server酱，消息展示不够直观，一直不满意，直到偶尔间看到这个项目，简直太棒了！
我的应用场景是多台机器运行自动化脚本，用来监控异常发出通知，但现在是每台机器都要部署 有点麻烦，如果是可以搭建服务端，只需要在一台机器部署 可以方便很多。可是搭建服务端这块自己不懂，fastapi看了两天没学会……

**Comment by GentleCP** [comment]
你好，我的理解是你希望以一个服务器为专门的消息收发中心，其他的任务服务器与其通信，其与你的移动端通信， 但是你又不会用fastapi在通信服务器上创建http get/post能力，是这个意思吧。

fastapi的使用我在`corpwechatbot/web.py`中写了例子，不过那个是为了实现和企业微信回调，并且由于时间原因，代码比较简陋，后续我会优化这块内容，不过并不会很快上线（因为个人学业压力）。我会尽量提供简单的实现接口和配套的文档，同时后期我打算针对`corpwechatbot`提供各种不同使用场景的例子，可能整个文档会有较大改动，但这些由于不是`corpwechatbot`的核心功能，包括用`fastapi`搭建服务端，所以你如果着急的话，建议阅读`corpwechatbot/web.py`这部分代码（其实并不难。。。），如果不急的话，可以耐心等待后续更新:)

**Comment by photkey** [comment]
感觉您理解的是对的，但是由于我半路出家 只自学了一点自动化脚本方面的知识，所以你的表述对我来说有点太专业了，我怕我理解错您的意思了。我再简单说一下 我的需求，大概意思就是可以搭建一个自己的server酱，只需要向服务端发出post/get请求，就能发出通知。
我是没那么着急的，因为我的自动化脚本还没有写完善，期待后续更新。谢谢你的回复，GitHub 真是个好地方。

**Comment by GentleCP** [comment]
那我懂了，按照`fastapi` 创建一个消息转发接口是可行的，或者你可以直接用server酱提供的开源版，可以直接部署自己的server酱，但我没部署过，官方貌似是用php实现的，原谅我对php并不了解。
