### ISSUE TITLE
access_token missing

### ISSUE THREAD

**Issue by cilicilis** [GentleCP/corpwechat-bot#7]
![image](https://user-images.githubusercontent.com/34146480/125151474-066c8600-e179-11eb-82e2-591c26cca9a9.png)
之前用您的包好好的，结果我在新服务器上配置的时候，就出现了这样的问题，查阅了网上很多说明都没有得到解决，请问我该怎么办？而且配置好您的包之后，需要自己添加一个token.txt文件，我很迷茫，我应该把token.txt文件放在哪？而且文件里的内容我改填写什么？

**Comment by GentleCP** [comment]
AppMsgSender发现应用消息需要通过一个 `access_token` 通信，这个token是通过你的企业id(corpid), 应用id(agent_id)，应用密钥(corp_secret),向企业微信请求得到的，`corpwechatbot` 会自动根据你提供的三个信息，在实例化的时候请求这个 `token` 并存储到本地文件，方便后续使用。

你在创建一个`AppMsgSender的时候，应该得到如下结果：
![image](https://user-images.githubusercontent.com/38175267/125153108-2a819480-e184-11eb-8bd1-86d25377b52e.png)
在这里因为我将三个参数的配置写在了本地，因此可以直接实例化，否则你应该按如下创建实例：
```python
from corpwechatbot.app import AppMsgSender
# from corpwehcatbot import AppMsgSender  # both will work

app = AppMsgSender(corpid='',  # 你的企业id
                   corpsecret='',  # 你的应用凭证密钥
                   agentid='')   # 你的应用id

# 如果你在本地配置添加了企业微信本地配置文件，也可以直接初始化AppMsgSender，而无需再显式传入密钥参数
# app = AppMsgSender()

```
简而言之，这个` token.txt` 不是你手动填的，是自动获取的，具体请参考 https://github.com/GentleCP/corpwechat-bot/blob/master/docs/usage.md

**Comment by cilicilis** [comment]
![image](https://user-images.githubusercontent.com/34146480/125158427-ab9c5400-e1a3-11eb-981d-577ea60e89eb.png)

谢谢！我已经解决了，这里的TOKEN_PATH地址，在服务器上部署的时候必须写绝对地址（绝对地址选择文件当前路径），要不然就出现下面的错误。
在电脑本机运行的时候可能不会出现这样的错误，但是在服务器上肯定会出现问题的。
![image](https://user-images.githubusercontent.com/34146480/125158469-f6b66700-e1a3-11eb-8479-c09ea6dcc838.png)

**Comment by GentleCP** [comment]
跟服务器没啥关系，看这个错误是你没有读取该文件的权限，建议pip安装的时候加上 --user
